### ISSUE TITLE
how to: collaborate with outside parties (like food bank project)

### ISSUE THREAD

**Issue by machikoyasuda** [maptimeLA/howto_holda_meeting_guide#3]
would be great for someone to write tips for how to collaborate with outside groups, like the food bank project ... @jrhutson

**Comment by JRHutson** [comment]
@machikoyasuda I'll start putting some ideas together. After being out of touch for a bit, I found out this week that Andy isn't at the Food Bank anymore. So...not sure if there's a lesson in there.

**Comment by machikoyasuda** [comment]
@JRHutson thanks for the comment update :) instead of a "how to" angle, then, you could do something more like a "project post mortem" where you outlined what you did, when, how, and what they did, and how we came up with the agreement/terms, etc.. and what problems/issues we had, if any, and what lessons are learned, what to try next time..
